### ISSUE TITLE
After clicking replay the replay icon stays on screen

### ISSUE THREAD

**Issue by David-Mulder** [gorork/paper-audio-player#10] opened 2015-11-24 17:09 UTC
Per title

![image](https://cloud.githubusercontent.com/assets/46602/11374456/7501b2a4-92d6-11e5-8c47-95a0afce638f.png)

**Comment by gorork** [comment] 2015-12-06 20:35
@David-Mulder I can't reproduce this one. What browser do you use?

**Comment by David-Mulder** [comment] 2015-12-06 20:49
@gorork Whatever else changed it seems to be fixed now, but you should take a look at commit a45c0ba none the less as it fixes the use of inline styling and use of `on-click` listeners.

**Comment by gorork** [comment] 2015-12-06 20:55
@David-Mulder Ok, good, closing this issue.

Btw, I kept 2 of your commits unmerged for now, because I want to incorporate them into the features I'm currently working locally. I'll merge them a bit later. :)

**Closed as completed** 2015-12-06 20:57 UTC
