### ISSUE TITLE
 The Play and Pause buttons do not work

### ISSUE THREAD

**Issue by EmmanuelMartinez** [gorork/paper-audio-player#29] opened 2016-10-31 23:38 UTC
The Play and Pause buttons do not work, shown 3 at the same time, hide function does not work.

What could be my problem?
 And

How I can put a notice of loading?

This is the project I'm working:  http://2016.socialrhythm.mx/discografia

Thanks for the help
Kind regards

![captura de pantalla 2016-10-31 a la s 5 32 04 p m](https://cloud.githubusercontent.com/assets/23070204/19875211/71563d92-9f90-11e6-8783-e25c0b50d935.png)

**Comment by gorork** [comment] 2016-11-01 00:52
@EmmanuelMartinez What player version are you using?

Judging by the look of the player in your project, it's not the latest production version. The round play/pause icons are from very old versions, while volume control is not yet merged into the master branch. My guess is that these modifications introduced this bug.

**Comment by EmmanuelMartinez** [comment] 2016-11-01 03:56
the version is 1.1.0, install it from bower, I work the volume control,
before control volume had the problem

Excuse my English so bad

**Comment by EmmanuelMartinez** [comment] 2016-11-01 05:15
updated, installing files in zip and bower and the result is the same.
![captura de pantalla 2016-10-31 a la s 11 15 20 p m](https://cloud.githubusercontent.com/assets/23070204/19880121/f35a7f86-9fbf-11e6-9c43-ab71ad6b23ec.png)

I hope you can help me

**Comment by gorork** [comment] 2016-11-02 08:49
How do you pass a track url to the player? There is no `src` attribute at the `<paper-audio-player>` element in your project. 

Try updating the `src` attribute on the player itself.

**Comment by EmmanuelMartinez** [comment] 2016-11-02 22:47
Pass the url with a variable
`<paper-audio-player src="{{playsrc}}" title="{{playtitle}}" ></paper-audio-player>`

I put the direct link and did not work
`<paper-audio-player src="/audio/Igual_que_tu.mp3" title="{{playtitle}}" ></paper-audio-player>`

the url works that the song is played, you can check
http://2016.socialrhythm.mx/discografia

**Comment by gorork** [comment] 2016-11-03 05:01
Yes, this should work as expected. Unfortunately, I can't reproduce this behaviour on my side. Could you create a minimally-working plunker/codepen that reproduces this issue?

**Comment by EmmanuelMartinez** [comment] 2016-11-03 17:33
I attached the code of the component:
only have to change the variable playsrc and playtitle
"Reproduccir" is a function that will be observed when changing song, does not affect whether remove
[sr-audio-play.html.zip](https://github.com/gorork/paper-audio-player/files/569683/sr-audio-play.html.zip)

**Comment by EmmanuelMartinez** [comment] 2016-11-03 18:17
https://github.com/EmmanuelMartinez/prueba-paper-audio/blob/master/prueba-paper-audio/sr-audio-play.html

**Comment by EmmanuelMartinez** [comment] 2016-11-09 17:25
In firefox they are working, I think the problem is `hidden$`

**Comment by gorork** [comment] 2016-11-12 23:14
We need to reproduce the same behaviour in a minimal environment. Could you create a live example with the same bug on [Plunker](https://plnkr.co/) or [Codepen](https://codepen.io/).

**Comment by EmmanuelMartinez** [comment] 2016-11-17 20:12
It has been difficult for me to upload the project to codeopen because I do not know it, excuse my ignorance.
But I discovered, reviewing the project and commenting this line already works
`window.Polymer = {lazyRegister: true, dom: 'shadow'};`
But I have discovered, reviewing the project, that if I comment this line in index.html file the buttons work.

Who's got an idea?

**Comment by gorork** [comment] 2017-01-25 07:13
Closing this issue for now, as it's more likely environment-related and not reproduced.

**Closed as completed by gorork** 2017-01-25 07:13 UTC
Labels: investigation needed
